[package]
name = "kmer"
version = "0.1.0"
authors = ["Jason Yamada-Hanff <jyamada1@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
log = "0.4"
loggerv = "0.7.2"
structopt = "0.3"
clap-verbosity-flag = "0.3.2"
bio = "0.37"
thiserror = "1.0.29"

[dev-dependencies]
tempfile = "3"